[package]
name = "bevy_games"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", features = [
    "dynamic_linking",
    "bevy_dev_tools",
    "shader_format_spirv",
] }
bevy-inspector-egui = "0.25"
bevy_blendy_cameras = "0.4"
serde = "1.0"
serde_json = "1.0"

[[bin]]
path = "src/others/blender_as_bevy_editor/main.rs"
name = "blender_as_bevy_editor"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

